import {strict as assert} from "node:assert";
import {test} from "node:test";

import {interpolate, score, timeWeightedCap} from "../src/dcs1.ts";
import type {MandateHistory} from "../src/types.ts";

const DAY = 86_400n;

/**
 * Expected values here are computed BY HAND from spec/DCS-1.md, not captured from this
 * implementation. A golden file generated by the code under test proves only that the code
 * agrees with itself; these vectors are what make the spec the authority.
 */

function history(overrides: Partial<MandateHistory> = {}): MandateHistory {
  return {
    allowedActs: 0n,
    firstActTime: null,
    asOfTime: 1_800_000_000n,
    denials: [],
    capSegments: [],
    ...overrides,
  };
}

test("a mandate with no history scores 200", () => {
  // raw = base 200_000; no terms, no breach. 200_000 * 1000 / 1e6 = 200.
  const result = score(history());
  assert.equal(result.score, 200);
  assert.equal(result.experiencePpm, 0n);
  assert.equal(result.agePpm, 0n);
  assert.equal(result.authorityPpm, 0n);
});

test("100 acts, 180 days old, 1e18 wei of authority scores 690", () => {
  // E = 400_000 (breakpoint), A = 1_000_000 (saturated), U = 500_000 (breakpoint).
  // raw = 200_000 + (350_000*400_000 + 250_000*1_000_000 + 200_000*500_000) / 1e6
  //     = 200_000 + 490_000 = 690_000 -> 690.
  const asOf = 1_800_000_000n;
  const result = score(
    history({
      allowedActs: 100n,
      firstActTime: asOf - 180n * DAY,
      asOfTime: asOf,
      capSegments: [{cap: 10n ** 18n, durationSeconds: 180n * DAY}],
    }),
  );
  assert.equal(result.experiencePpm, 400_000n);
  assert.equal(result.agePpm, 1_000_000n);
  assert.equal(result.authorityPpm, 500_000n);
  assert.equal(result.score, 690);
});

test("three recent hard breaches zero the score whatever else is true", () => {
  // D = min(1e6, 3 * 340_000) = 1e6, so the settled score is 0. Conduct is a veto.
  const asOf = 1_800_000_000n;
  const result = score(
    history({
      allowedActs: 100n,
      firstActTime: asOf - 180n * DAY,
      asOfTime: asOf,
      capSegments: [{cap: 10n ** 18n, durationSeconds: 180n * DAY}],
      denials: [
        {rule: "PerActionCap", timestamp: asOf},
        {rule: "TargetNotAllowed", timestamp: asOf},
        {rule: "SelectorForbidden", timestamp: asOf},
      ],
    }),
  );
  assert.equal(result.breachPpm, 1_000_000n);
  assert.equal(result.score, 0);
});

test("a hard breach 65 days old has halved twice: 690 -> 631", () => {
  // halvings = floor(65/30) = 2, weight = 340_000 >> 2 = 85_000.
  // 690_000 * (1e6 - 85_000) / 1e6 = 631_350 -> 631.
  const asOf = 1_800_000_000n;
  const result = score(
    history({
      allowedActs: 100n,
      firstActTime: asOf - 180n * DAY,
      asOfTime: asOf,
      capSegments: [{cap: 10n ** 18n, durationSeconds: 180n * DAY}],
      denials: [{rule: "PerActionCap", timestamp: asOf - 65n * DAY}],
    }),
  );
  assert.equal(result.breachPpm, 85_000n);
  assert.equal(result.score, 631);
});

test("a soft breach weighs far less than a hard one", () => {
  const asOf = 1_800_000_000n;
  const base = {
    allowedActs: 100n,
    firstActTime: asOf - 180n * DAY,
    asOfTime: asOf,
    capSegments: [{cap: 10n ** 18n, durationSeconds: 180n * DAY}],
  };
  const soft = score(history({...base, denials: [{rule: "RateCap", timestamp: asOf}]}));
  const hard = score(history({...base, denials: [{rule: "PerActionCap", timestamp: asOf}]}));

  assert.equal(soft.breachPpm, 50_000n);
  assert.equal(hard.breachPpm, 340_000n);
  assert.ok(soft.score > hard.score);
});

test("experience interpolates linearly between log-spaced breakpoints", () => {
  // 200_000 + (50-10) * (400_000-200_000) / (100-10) = 200_000 + 88_888 = 288_888.
  assert.equal(score(history({allowedActs: 50n})).experiencePpm, 288_888n);
});

test("experience saturates and never exceeds one", () => {
  assert.equal(score(history({allowedActs: 10_000_000n})).experiencePpm, 1_000_000n);
});

test("age saturates at 180 days", () => {
  const asOf = 1_800_000_000n;
  const old = score(history({firstActTime: asOf - 3650n * DAY, asOfTime: asOf}));
  assert.equal(old.agePpm, 1_000_000n);
});

test("time-weighted cap weights by duration, not by count", () => {
  // (10 * 90 + 0 * 10) / 100 = 9
  assert.equal(
    timeWeightedCap([
      {cap: 10n, durationSeconds: 90n},
      {cap: 0n, durationSeconds: 10n},
    ]),
    9n,
  );
  assert.equal(timeWeightedCap([]), 0n);
  assert.equal(timeWeightedCap([{cap: 5n, durationSeconds: 0n}]), 0n);
});

test("interpolate is flat outside the table", () => {
  const table = [
    [0n, 0n],
    [10n, 100n],
  ] as const;
  assert.equal(interpolate(table, -5n), 0n);
  assert.equal(interpolate(table, 0n), 0n);
  assert.equal(interpolate(table, 5n), 50n);
  assert.equal(interpolate(table, 999n), 100n);
});

test("the score always lands within 0..1000", () => {
  const asOf = 1_800_000_000n;
  for (const acts of [0n, 1n, 999n, 10n ** 9n]) {
    for (const denialCount of [0, 1, 5, 50]) {
      const denials = Array.from({length: denialCount}, () => ({
        rule: "PerActionCap" as const,
        timestamp: asOf,
      }));
      const result = score(
        history({
          allowedActs: acts,
          firstActTime: asOf - 400n * DAY,
          asOfTime: asOf,
          capSegments: [{cap: 10n ** 24n, durationSeconds: 400n * DAY}],
          denials,
        }),
      );
      assert.ok(result.score >= 0 && result.score <= 1000, `out of range: ${result.score}`);
    }
  }
});

test("adding a denial never increases the score", () => {
  const asOf = 1_800_000_000n;
  const base = {
    allowedActs: 1_000n,
    firstActTime: asOf - 90n * DAY,
    asOfTime: asOf,
    capSegments: [{cap: 10n ** 19n, durationSeconds: 90n * DAY}],
  };
  let previous = score(history(base)).score;
  const denials: MandateHistory["denials"] = [];
  for (let i = 0; i < 6; i++) {
    denials.push({rule: "SpendWindowCap", timestamp: asOf - BigInt(i) * 10n * DAY});
    const next = score(history({...base, denials: [...denials]})).score;
    assert.ok(next <= previous, `score rose from ${previous} to ${next}`);
    previous = next;
  }
});

test("the empty event set hashes to keccak256 of nothing", async () => {
  // spec/DCS-1.md §6. Verified live against Monad testnet on a mandate with no logs.
  const {inputHash} = await import("../src/inputHash.ts");
  assert.equal(
    inputHash([]),
    "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
  );
});

test("inputHash is order-independent in input but order-dependent in meaning", async () => {
  const {inputHash} = await import("../src/inputHash.ts");
  const a = {blockNumber: 1n, logIndex: 0, topics: ["0x01" as const], data: "0x" as const};
  const b = {blockNumber: 1n, logIndex: 1, topics: ["0x02" as const], data: "0x" as const};

  // Events are sorted by (blockNumber, logIndex) before hashing, so the caller's ordering
  // cannot change the result - which is what makes two independent indexers agree.
  assert.equal(inputHash([a, b]), inputHash([b, a]));

  // But a different event set must hash differently.
  assert.notEqual(inputHash([a]), inputHash([a, b]));
});

test("a stale asOf block silently changes the score, which is why replay disables caching", () => {
  // Regression note for the bug found by running demo/beat.ts against a live chain: viem
  // caches getBlockNumber, so a replay moments after a denial landed scored the chain as it
  // was before it. The scorer itself is honest - given the truncated history it returns the
  // pre-denial number - which is precisely why the truncation had to be fixed upstream.
  const asOf = 1_800_000_000n;
  const base = {
    allowedActs: 3n,
    firstActTime: asOf - 1n,
    asOfTime: asOf,
    capSegments: [{cap: 5n * 10n ** 18n, durationSeconds: 3601n}],
  };
  const withoutDenial = score(history(base));
  const withDenial = score(
    history({...base, denials: [{rule: "TargetNotAllowed", timestamp: asOf}]}),
  );

  assert.equal(withoutDenial.score, 331);
  assert.equal(withDenial.score, 218);
  assert.equal(withDenial.breachPpm, 340_000n);
});
